import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/header.components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar /> {/* Navbar is fixed and will stay at the top */}
        <main className="pt-16">{children}</main> {/* Add padding to avoid overlap */}
      </body>
    </html>
  );
}