import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../components/common.components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-cover bg-no-repeat bg-center`}
        style={{ backgroundImage: `url('/images/nature-cover.jpg')` }}
      >
        <Navbar />        
        {children}
      </body>
    </html>
  );
}